title: 工具
subtitle: 工欲善其事，必先利其器

template: forum
categories:
  - name: 云服务平台
    icon: fas fa-cloud
    sites:
    - name: Vercel
      url: https://vercel.com/
      icon: fas fa-server
      description: 前端部署平台
    - name: Cloudflare
      url: https://www.cloudflare.com/zh-cn/
      icon: fab fa-cloudflare
      description: 赛博活佛
    - name: 阿里云
      url: https://cn.aliyun.com/
      icon: fas fa-cloud
      description: 有个图床还在用
  - name: 开发
    icon: fas fa-code
    sites:
      - name: csacademy
        url: https://csacademy.com/app/graph_editor/
        icon: fas fa-project-diagram
        description: 用于算法题目中生成图论题目的预览
      - name: 坐标轴绘图
        url: https://www.geogebra.org/classic
        icon: fas fa-ruler-combined
        description: 方便快捷地生成平面几何模型
      - name: 在线汇编
        url: https://godbolt.org/
        icon: fas fa-microchip
        description: 优化代码性能，分析软件漏洞
      - name: 目录结构树生成器
        url: https://directory-structure.wuc0714.top/
        icon: fas fa-sitemap
        description: 用于文档的目录分析
      - name: Linux脚本工具箱
        url: https://kejilion.sh/index-zh-CN.html
        icon: fab fa-linux
        description: 只需一行命令，即可开启您的Linux管理之旅
      - name: json工具库
        url: https://www.json.cn/json/
        icon: fas fa-code
        description: 和json相关的找它就对了
  - name: 设计平台
    icon: fas fa-palette
    sites:
      - name: canva
        url: https://www.canva.cn/
        icon: fas fa-paint-brush
        description: 在线平面设计
      - name: canva国际版
        url: https://www.canva.com/
        icon: fas fa-paint-brush
        description: 白嫖教育优惠但中文资源少
      - name: excalidraw
        url: https://excalidraw.com/
        icon: fas fa-pencil-ruler
        description: 手绘风格图表制作
      - name: AI抠图
        url: https://segment-anything.com/demo
        icon: fas fa-cut
        description: 图像处理某篇论文的演示，拿来做抠图挺好用
      - name: 在线拼图工具
        url: https://img.ops-coffee.cn/zh/app/
        icon: fas fa-puzzle-piece
        description: 朋友圈九宫格拼图工具 
  - name: 格式转化
    icon: fas fa-exchange-alt
    sites:
      - name: IT Tools
        url: https://tools.adguy.top/
        icon: fas fa-tools
        description: 有一些基本的转换工具
      - name: convert tools
        url: https://converttool.org/zh-cn/
        icon: fas fa-sync-alt
        description: 东西挺全，但据说效果一般
      - name: json工具库
        url: https://www.json.cn/json/
        icon: fas fa-code
        description: 和json相关的找它就对了
      - name: 图片转Excel
        url: https://docsmall.com/image-to-excel
        icon: fas fa-file-excel
        description: 暂时免费
  - name: 薅羊毛
    icon: fas fa-gift
    sites:
      - name: 商品历史价格查询
        url: https://www.hisprice.com/
        icon: fas fa-chart-line
        description: 看清虚假折扣
      - name: Steam挂刀行情
        url: https://www.iflow.work/
        icon: fab fa-steam
        description: Steam倒余额
      - name: LinuxDo薅羊毛专区
        url: https://linux.do/c/welfare/36
        icon: fas fa-percent
        description: 论坛薅羊毛版块    
      - name: 学生证生成
        url: https://student-id.pages.dev/
        icon: fas fa-id-card
        description: 白嫖教育优惠
      
