title: 工具
subtitle: 工欲善其事，必先利其器

template: forum
categories:
  - name: 云服务平台
    icon: 
    sites:
    - name: Vercel
      url: https://vercel.com/
      icon: 
      description: 前端部署平台
    - name: Cloudflare
      url: https://www.cloudflare.com/zh-cn/
      icon:
      description: 赛博活佛
    - name: 阿里云
      url: https://cn.aliyun.com/
      icon:
      description: 有个图床还在用
  - name: 设计平台
    icon: 
    sites:
      - name: canva
        url: https://www.canva.cn/
        icon:
        description: 在线平面设计
      - name: canva国际版
        url: https://www.canva.com/
        icon:
        description: 白嫖教育优惠但中文资源少
      - name: excalidraw
        url: https://excalidraw.com/
        icon:
        description: 手绘风格图表制作
      
