- name: 首页
  icon: fas fa-home
  id: home
  active: true
- name: AI
  icon: fas fa-robot
  id: ai
- name: 论坛
  icon: fas fa-comments
  id: forum
- name: 特别关注
  icon: fas fa-users
  id: friends
- name: 书签
  icon: fas fa-bookmark
  id: bookmarks 